#!/usr/bin/env bash
stty -ixon # Disable ctrl-s and ctrl-q.
shopt -s autocd #Allows you to cd into directory merely by typing the directory name.
HISTSIZE= HISTFILESIZE= # Infinite history.
export PS1="\[$(tput bold)\]\[$(tput setaf 1)\][\[$(tput setaf 3)\]\u\[$(tput setaf 2)\]@\[$(tput setaf 4)\]\h \[$(tput setaf 5)\]\W\[$(tput setaf 1)\]]\[$(tput setaf 7)\]\\$ \[$(tput sgr0)\]"

extract () {
    if [ -f $1 ] ; then
        case $1 in
            *.tar.bz2) tar xvij $1;;
            *.tar.gz) tar xvzf $1;;
            *.bz2) bunzip2 $1;;
            *.rar) unrar x $1;;
            *.gz) gunzip $1;;
            *.tar) tar xvf $1;;
            *.tbz2) tar xvjf $1;;
            *.tgz) tar xvzf $1;;
            *.zip) unzip $1;;
            *.Z) uncompress $1;;
            *.7z) 7z x $1;;
            *.xz) unxz $1;;
            *.exe) cabextract $1;;
            *.tar.lrz) lrztar -d $1;;
            *.lrz) lrzip -d $1;;
            *) echo "don't know how to extract '$1'...";;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}

[ -f "$HOME/.config/aliasrc" ] && source "$HOME/.config/aliasrc"
