#!/usr/bin/fish

if test -f "$HOME/.xprofile"
  source "$HOME/.xprofile"
  xrdb -merge -I$HOME ~/.Xresources
end

set -x QT_QPA_PLATFORMTHEME qt6ct
set -x ANKI_NOHIGHDPI 0
set -x QT_FONT_DPI 91
set -x MOZC_IBUS_CANDIDATE_WINDOW ibus
set -x FREETYPE_PROPERTIES 'cff:no-stem-darkening=0 autofilter:no-stem-darkening=0'
set -x TZ 'Europe/London'
exec xmonad 
