[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "term"
serifs = "sans"
no-cv-ss = false
export-glyph-names = true

  [buildPlans.iosevka-custom.variants]
  inherits = "ss08"

    [buildPlans.iosevka-custom.variants.design]
    capital-a = "straight-serifless"
    capital-b = "more-asymmetric-interrupted-serifless"
    capital-c = "serifless"
    capital-d = "standard-serifless"
    capital-e = "serifless"
    capital-f = "serifless"
    capital-g = "toothed-serifless-hooked"
    capital-i = "serifless"
    capital-j = "serifed"
    capital-k = "straight-serifless"
    capital-m = "hanging-serifless"
    capital-n = "standard-serifless"
    capital-p = "open-serifless"
    capital-q = "detached-bend-tailed"
    capital-r = "straight-open-serifless"
    capital-s = "serifless"
    capital-u = "toothless-rounded-serifless"
    capital-v = "straight-serifless"
    capital-w = "straight-serifless"
    capital-x = "straight-serifless"
    capital-y = "straight-serifless"
    capital-z = "straight-serifless"
    f = "extended"
    g = "double-storey-open"
    i = "tailed-serifed"
    j = "hooky"
    k = "straight-serifless"
    l = "tailed-serifed"
    t = "bent-hook"
    v = "straight-serifless"
    w = "straight-serifless"
    x = "straight-serifless"
    y = "straight-serifless"
    z = "straight-serifless"
    long-s = "bent-hook-descending"
    eszet = "sulzbacher-serifless"
    capital-delta = "straight"
    lower-delta = "flat-top"
    lower-iota = "tailed-serifed"
    capital-lambda = "straight-serifless"
    lower-lambda = "straight"
    lower-mu = "toothed-serifless"
    lower-xi = "flat-top"
    lower-tau = "tailed"
    lower-chi = "straight-serifless"
    cyrl-capital-zhe = "symmetric-connected"
    cyrl-zhe = "symmetric-connected"
    cyrl-capital-ka = "symmetric-touching-serifless"
    cyrl-ka = "symmetric-touching-serifless"
    cyrl-el = "straight"
    cyrl-capital-u = "straight-serifless"
    cyrl-u = "straight-serifless"
    cyrl-yery = "corner-tailed"
    cyrl-capital-ya = "straight-open-serifless"
    cyrl-ya = "straight-open-serifless"
    zero = "slashed"
    one = "no-base"
    four = "semi-open"
    five = "oblique-arched"
    six = "straight-bar"
    seven = "straight-serifless"
    nine = "straight-bar"
    asterisk = "penta-high"
    underscore = "high"
    caret = "high"
    paren = "flat-arc"
    brace = "curly"
    guillemet = "curly"
    number-sign = "slanted-tall"
    ampersand = "et-toothed"
    at = "threefold"
    dollar = "through"
    percent = "rings-segmented-slash"
    question = "smooth"
    pilcrow = "low"
    cent = "through"
    partial-derivative = "curly-bar"
    lig-neq = "slightly-slanted"

    [buildPlans.iosevka-custom.variants.italic]
    capital-j = "serifed"
    capital-v = "straight-serifless"
    a = "double-storey-tailed"
    d = "tailed-serifless"
    e = "rounded"
    f = "tailed"
    i = "tailed"
    j = "serifed"
    k = "cursive-serifless"
    l = "tailed-serifed"
    t = "bent-hook"
    u = "tailed-serifless"
    v = "straight-serifless"
    y = "cursive-serifless"
    long-s = "bent-hook-tailed"
    eszet = "sulzbacher-tailed-serifless"
    lower-delta = "rounded"
    lower-iota = "tailed-serifed"
    lower-mu = "tailed-serifless"
    lower-tau = "tailed"
    cyrl-u = "cursive-serifless"
    cyrl-ef = "cursive"
    cyrl-che = "tailed"
    cyrl-yeri = "cursive"
    cyrl-yery = "cursive-tailed"
    guillemet = "curly"
    ascii-single-quote = "straight"
    micro-sign = "tailed-serifless"

  [buildPlans.iosevka-custom.ligations]
  inherits = "haskell"
